import Head from "next/head";
import Header from "../components/Header/Header";
import Banner from "../components/Banner";
import Footer from "../components/Footer/Footer";
import CatalogPreview from "../components/catalog/CatalogPreview";
import HomeContent from "../components/catalog/HomeContent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>
      <main>
        <Banner></Banner>
        <CatalogPreview></CatalogPreview>
        <CatalogPreview></CatalogPreview>
        <HomeContent></HomeContent>
        <CatalogPreview></CatalogPreview>
        <CatalogPreview></CatalogPreview>
      </main>
      <Footer></Footer>
    </div>
  );
}
